### ISSUE TITLE
启动后报500

### ISSUE THREAD

**Issue by fyCoder1995** [TurboWay/big_screen#1]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/55522801/95725310-1585dc80-0caa-11eb-84ff-7e3339b45ffa.png">
[](url)

**Comment by TurboWay** [comment]
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/55522801/95725310-1585dc80-0caa-11eb-84ff-7e3339b45ffa.png">
> 
> [](url)

应该是你 data.py 中父类加了传参，继承的时候 却没有给这个传参赋值。
两种解决办法：
1.父类去掉传参
2.子类继承的时候，super().__init__(xx=xx) 这边需要加上你父类定义的参数

**Comment by fyCoder1995** [comment]
emmm...升级了python版本，重装了pip，然后就跑起来了，谢谢分享～
