### ISSUE TITLE
你好，我输入了python app.py 但是出错

### ISSUE THREAD

**Issue by rouor** [TurboWay/big_screen#5]
pip 安装没有问题，显示应该是安装成功了。
但是在终端输入 python app.py 显示错误：
python: can't open file 'app.py': [Errno 2] No such file or directory 
不知道是什么原因？

**Comment by TurboWay** [comment]
> pip 安装没有问题，显示应该是安装成功了。
> 但是在终端输入 python app.py 显示错误：
> python: can't open file 'app.py': [Errno 2] No such file or directory
> 不知道是什么原因？

路径不对，要进入项目里面，比如 cd big_screen
