### ISSUE TITLE
显示启动了，但是浏览器访问不了

### ISSUE THREAD

**Issue by fengduanqiao** [TurboWay/big_screen#6]
无法访问此网站
212.64.70.92 拒绝了我们的连接请求

**Comment by TurboWay** [comment]
> 无法访问此网站
> 212.64.70.92 拒绝了我们的连接请求

如果是部署到了云服务器，你可能需要设置一下安全组规则，才可以对外开放端口。具体的，你可以通过搜索引擎了解下步骤。

**Comment by fengduanqiao** [comment]
> > 无法访问此网站
> > 212.64.70.92 拒绝了我们的连接请求
> 
> 如果是部署到了云服务器，你可能需要设置一下安全组规则，才可以对外开放端口。具体的，你可以通过搜索引擎了解下步骤。

需要修改app.py里面启动flask设置host='0.0.0.0'就可以了，感谢！
