### ISSUE TITLE
wanted help

### ISSUE THREAD

**Issue by striver619** [TurboWay/big_screen#7]
![image](https://user-images.githubusercontent.com/51977051/111060618-3365a080-84d9-11eb-9bcd-a581d99044a3.png)

请问数据是从哪里获取的？并且是以何种方式传入？
@TurboWay 如果您有时间，可以聊一下嘛？

![image](https://user-images.githubusercontent.com/51977051/111060642-60b24e80-84d9-11eb-9d54-1aeddd0ffd2b.png)

我可以看到的这个data.py文件里面是已经写好的

**Comment by TurboWay** [comment]
> ![image](https://user-images.githubusercontent.com/51977051/111060618-3365a080-84d9-11eb-9bcd-a581d99044a3.png)
> 
> 请问数据是从哪里获取的？并且是以何种方式传入？
> @TurboWay 如果您有时间，可以聊一下嘛？
> 
> ![image](https://user-images.githubusercontent.com/51977051/111060642-60b24e80-84d9-11eb-9d54-1aeddd0ffd2b.png)
> 
> 我可以看到的这个data.py文件里面是已经写好的

数据都是从 data.py 的 SourceDataDemo 类或者其子类（参考 data_corp.py 或者 data_job.py）来导入的，具体的数据填充，你可以从任何地方（excel/csv/数据库）读取，只要格式保持一致即可。最后在 app.py 导入你自己的数据类，并设定路由即可，当然，你也可以直接覆盖  data.py 的 SourceDataDemo 类 。

**Comment by striver619** [comment]
> 数据都是从 data.py 的 SourceDataDemo 类或者其子类（参考 data_corp.py 或者 data_job.py）来导入的，具体的数据填充，你可以从任何地方（excel/csv/数据库）读取，只要格式保持一致即可。最后在 app.py 导入你自己的数据类，并设定路由即可，当然，你也可以直接覆盖 data.py 的 SourceDataDemo 类 。

比方说从csv文件获取，那要怎么做才能把数据导入到app.py中呐？
这属于Pandas数据分析范畴对吧，我还是有个疑问，为什么要把数据导入到app.py中？何不直接在app.py中引入csv等数据文件呐？

**Comment by striver619** [comment]
> 数据都是从 data.py 的 SourceDataDemo 类或者其子类（参考 data_corp.py 或者 data_job.py）来导入的，具体的数据填充，你可以从任何地方（excel/csv/数据库）读取，只要格式保持一致即可。最后在 app.py 导入你自己的数据类，并设定路由即可，当然，你也可以直接覆盖 data.py 的 SourceDataDemo 类 。

比方说从csv文件获取，那要怎么做才能把数据导入到app.py中呐？
这属于Pandas数据分析范畴对吧，我还是有个疑问，为什么要把数据导入到app.py中？何不直接在app.py中引入csv等数据文件呐？

**Comment by striver619** [comment]
![image](https://user-images.githubusercontent.com/51977051/111062300-06b68680-84e3-11eb-87d5-3a304738bbf1.png)

thank you!

**Comment by TurboWay** [comment]
将 data.py 数据类分离，仅仅是为了使用上更方便，代码结构更清晰。当然放一起也是可以的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月14日(星期天) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboWay/big_screen] wanted help (#7)





  
数据都是从 data.py 的 SourceDataDemo 类或者其子类（参考 data_corp.py 或者 data_job.py）来导入的，具体的数据填充，你可以从任何地方（excel/csv/数据库）读取，只要格式保持一致即可。最后在 app.py 导入你自己的数据类，并设定路由即可，当然，你也可以直接覆盖 data.py 的 SourceDataDemo 类 。
  
比方说从csv文件获取，那要怎么做才能把数据导入到app.py中呐？
 这属于Pandas数据分析范畴对吧，我还是有个疑问，为什么要把数据导入到app.py中？何不直接在app.py中引入csv等数据文件呐？

**Comment by striver619** [comment]
![image](https://user-images.githubusercontent.com/51977051/111063676-01f5d080-84eb-11eb-8089-0d1f9fbbe8f0.png)

![image](https://user-images.githubusercontent.com/51977051/111063705-310c4200-84eb-11eb-9bb6-dfd187c4014b.png)

![image](https://user-images.githubusercontent.com/51977051/111063695-22be2600-84eb-11eb-96d0-33d873584563.png)

![image](https://user-images.githubusercontent.com/51977051/111063699-2b166100-84eb-11eb-8913-840745c8e0a7.png)

**Comment by striver619** [comment]
```
![image](https://user-images.githubusercontent.com/51977051/111063705-310c4200-84eb-11eb-9bb6-dfd187c4014b.png)

![image](https://user-images.githubusercontent.com/51977051/111063695-22be2600-84eb-11eb-96d0-33d873584563.png)

![image](https://user-images.githubusercontent.com/51977051/111063699-2b166100-84eb-11eb-8913-840745c8e0a7.png)
```
